name: 04 - Reusing Workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/04-reusable-workflow.yml
    with:
      who-to-greet: '@octocat'
      
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
